{% set version = "1.9.1" %}

package:
  name: pyophidia
  version: {{ version }}

source:
  url: https://github.com/OphidiaBigData/PyOphidia/archive/v{{ version }}.tar.gz
  sha256: 46f8dc23a0a3a75a7c999886319491c60b1fc447cdab3c5faf1dd571f0038c91

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6

test:
  imports:
    - PyOphidia

about:
  home: http://github.com/OphidiaBigData/PyOphidia
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: PyOphidia is a Python package for interacting with the Ophidia framework.

extra:
  recipe-maintainers:
    - doutriaux1
    - eldoo
    - minomicetto
    - aledanca
    - sandrofiore
