{% set version = "1.11" %}

package:
  name: pyophidia
  version: {{ version }}

source:
  url: https://github.com/OphidiaBigData/PyOphidia/archive/v{{ version }}.tar.gz
  sha256: 65b730f264e1c15058156d80ead3d182edd3c3df99b1dba05fb84daa12a5f0f2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6

test:
  imports:
    - PyOphidia

about:
  home: http://github.com/OphidiaBigData/PyOphidia
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: PyOphidia is a Python package for interacting with the Ophidia framework.

extra:
  recipe-maintainers:
    - doutriaux1
    - eldoo
    - minomicetto
    - aledanca
    - sandrofiore
