travis:
  secure:
    BINSTAR_TOKEN: RpCAwL4T4JdZixwo2qec220PIvGSr3T51eec+ycG9aiTzDB54+7ep/k8vqXDgdZmVqxPL+or9shWhMvq9XO17AeXNr/X8GWDts9cRK3oOkt6YJ7MM2ZLCdEupdxzLSFwCF6zEeJ6C3+xk62Ybho/NFmAyUzn62YDNq1SNzSXuog3bsHvc+txI5NH5boK9IDu1iifag62XgS+9yevzCW1YqFl2+xsBVkspqsXfMDlgI2ogkEmXgIBx2QZnAmTzbPzWaRRJu+nJpINeM4rjcXgPUigBU5pZBHBQUV9G4p1/RraeOtKy5eUEhFNFQBVe+xQ+5H4gvHbdPYJU08nWFMXUoNsA3uoZelu+OwsYMB6LdDbPLsAYA4YYmQmoUq20xOzXGHxs6yriBKiri20/HKWrRXLQ1eq0yjAGW31NgZs2/Z5AxxKrBtZaw+p+fSzGN+1FjX55ilBzGYgFE1QqlACG3bCt75BDG48thobLFifjk6UkSLKfA4fVE5iJs82GzBgP2a1MCxuSbhNjrswAnAwldFvHh73fSDJwLhFN9FAmFpBv6/3E2V0PQ2XEyUfnj97zr86z4wZImIGUm65dcvqWGUkd8H9vvzU5myk+eLN8uSMT15qoTzW84CjH5z9Keb0HGWKiXbKq63KyxtkQEk5BzZOTrjm9WRYWZpG9WmJlMI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
